<a href="https://www.kaggle.com/code/edwardakalarrywelch/very-basic-numpy-notes?scriptVersionId=91398080" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>


<a id='2'></a>
# <p style="background-color:#1B03A3; font-family:newtimeroman; color:white; font-size:120%; text-align:center;border-radius: 24px 0;">1. Very Basic Numpy Notes</p>

In [1]:
#import numpy as np
import numpy as np
import math

<a id='2'></a>
# <p style="background-color:#1B03A3; font-family:newtimeroman; color:white; font-size:120%; text-align:center;border-radius: 24px 0;">2. How to make a numpy array.</p>

In [2]:
# Use a list to create an array.
array_one = np.array([1, 2, 3])
print(array_one)

# print number of dimensions of a list using ndim.
print(array_one.ndim)

[1 2 3]
1


# Below, we create a 2X3 multi-dimensional array.


In [3]:
# Create a multi-dimensional array from a list of lists.
array_two_by_three = np.array([[1,2,3],[4,5,6]])
array_two_by_three

array([[1, 2, 3],
       [4, 5, 6]])

# Notice the list above contains two rows and 3 colums - a 2x3 array.

# Here, we can find the shape of our array.


In [4]:
# Use 'shape' to print the shape of an array.  

array_two_by_three.shape

(2, 3)

# The datatype of the items in the array are found using 'dtype'

In [5]:
# We can also check the type of items in the array
array_one.dtype

dtype('int64')

# You can use floats and integers in np arrays

In [6]:
another_array = np.array([4.3, 6.2, 1.1, 3.3])

# print the datatype and 'name' of the value in the array
another_array.dtype.name

'float64'

# Create an array by filling your chosen 'shape' with ones or zeros.

In [7]:
# Create and fill this array with zeros, a 2X3 array.
array_with_zeros = np.zeros((2,3))
print(array_with_zeros)

array_with_ones = np.ones((2,3))
print(array_with_ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Create a 3X3 array and fill it with random numbers


In [8]:
np.random.rand(3,3)

array([[0.18883887, 0.19116232, 0.97749273],
       [0.85348362, 0.45458707, 0.82925066],
       [0.77296933, 0.71998674, 0.51406699]])

# Create an array and use 'arrange' to fill an array with even numbers from 2 to 20.

In [9]:
even_array = np.arange(2, 20, 2)
even_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# Manipulating array elements with basic operations

In [10]:
# These operations apply to each element in the arrays.

array_one = np.array([10,20,30,40])
array_two = np.array([1, 2, 3,4])

# Subtraction
array_three = array_one - array_two
print(array_three)

# Multiplication
array_four = array_one * array_two
print(array_four)

[ 9 18 27 36]
[ 10  40  90 160]


# Numpy Boolean (True/False)

In [11]:
array_one = 50
print(array_one > 50)  # is array > 50?  No, so it returns 'False'

print(array_one)

False
50


# Matrix multiplication

In [12]:
array_one = np.array([2,2])
array_two = np.array([4,4])

# To multiply the entire array, use the @ symbol.

np.array_three = array_one @ array_two
print(array_one,array_two)
print(array_three)

[2 2] [4 4]
[ 9 18 27 36]


# Use 'sum' to sum array elements

In [13]:
array_one = np.array([1,2,3])

print(array_one.sum())

6


# Use 'mean' to find the mean of array elements.

In [14]:
print(array_one.mean())


2.0


# Use 'max' to find the max value in an array.


In [15]:
print(array_three.max())

36


# Use min to find the minimum value in an array

In [16]:
print(array_three.min())

9


# Indexing Arrays

In [17]:
# One dimensional arrays are similar to lists
array_one = np.array([4,7,1,4])
array_one[3]

# array_one at index three is the value 4

4

# Integer array indexing

In [18]:
# Two dimensiona arrays are indexed this way.
array_one = np.array([[1,2], [3, 4]])
print(array_one) # notice the shape and positions of the numbers

# the output is like this [[1 2]
#############             [3 4]]
# to print the 3 in this array, do this:
print(array_one[1,0])  # Remember, the 1 is the row, and the 0 is the column.  So, 1,0 returns the 
                       # value in the spot of row 1, column 0 - which is 3.  Also, remember, Python indexing starts at 0.

[[1 2]
 [3 4]]
3


# Slicing

In [19]:
# Slicing allows us to select parts of an array
array_one = np.array([3,4,5,7,9])
print(array_one[:3])  # here we 'slice' out the values from index 0 to index 2.  This can be confusing.
                      #  Just remember that Python indexing goes UP TO the last number, but doesn't include it.  
                      #  For example, index [:3] returns the values in index spots 0,1,2 which are 3,4,5

[3 4 5]


In [20]:
# or slice the 2nd and 3rd values with 1:3.  Confused yet?  
print(array_one[1:3])  # This returns the values 4,5. The 4 is in index 1, and the 5 is in index 2.

[4 5]


# Multi dimiensional array indexing

In [21]:
#multidimensional indexing
array_one = np.array([[3,4,5,6], [7,8,9,10]])
array_one

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [22]:
# to slice the 1st and 2nd values from the 3rd column which are 5 and 9
print(array_one[0:2,2])  # select 0:2 rows and 2 column.  this slices 5 and 9 out of rows 0,1 and column 2

[5 9]
